# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: 'A path to cinematic success'
tagline: 'A path to cinematic success' # For the tab title
description: 'Applied Data Analysis Project - EPFL '
url: http://hyde.getpoole.com # FIXME - Change this, but what does it do ?
baseurl: /

defaults:
  - scope:
      path: "images"
    values:
      image: true

author:
  name: 'The Armada Of Badass Empanadas'
  url: https://github.com/epfl-ada/ada-2023-project-thearmadaofbadassempanadas

paginate: 100

# Custom vars
# version: 2.1.0

github:
  repo: https://github.com/epfl-ada/ada-2023-project-thearmadaofbadassempanadas
