theme: jekyll-theme-minimal
title: Charting a path to cinematic success
description: A dive in an actress cinematic dream
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
